### ISSUE TITLE
Thanks for creating and definitely get the motivation

### ISSUE THREAD

**Issue by basarat** [remojansen/logo.ts#1]
However there is https://github.com/Microsoft/TypeScript/blob/master/doc/logo.svg available. 

I'm confused if I should use this one.

Good job though. Definitely looks better. :rose:

**Comment by remojansen** [comment]
Hi @basarat I guess you can use the one you like the most. My one looks cool on a laptop I must say :wink: 

I have [added a note](https://github.com/remojansen/logo.ts/commit/c1547d7c27babd93dda20b959807fc8f801d1d21) to the `readme.md` file to avoid potential confusions...

**Comment by basarat** [comment]
> My one looks cool on a laptop I must say

Agreed. The official TypeScript Logo doesn't feel like a logo :rose:

**Comment by remojansen** [comment]
@basarat looks like Anders Hejlsberg likes it too :smile: 

![](https://raw.githubusercontent.com/remojansen/logo.ts/master/stickers/Screen%20Shot%202016-03-31%20at%2000.05.02.png)

**Comment by basarat** [comment]
@remojansen I've started using it too : http://slides.com/basarat/reactjs-with-typescript#/ :rose:

**Comment by remojansen** [comment]
Looks nice next to the React logo :smile:
