### ISSUE TITLE
Only letters version logo

### ISSUE THREAD

**Issue by lifenautjoe** [remojansen/logo.ts#2]
Could we get a only letters version logo? 
The TS letters in the blue color, or If I could get the font name I'll do it and submit it over here.

Printing some shirts, a big square is not very heat friendly.

**Comment by remojansen** [comment]
If you have an svg editing tool you could create it taking https://github.com/remojansen/logo.ts/blob/master/ts.svg as base. The font is [`Neutra Text Bold`](https://github.com/voodootikigod/logo.js/issues/67). The colour is #007ACC.

**Comment by lifenautjoe** [comment]
Alright, expect PR

**Comment by remojansen** [comment]
@thefabulousdev thanks!

**Comment by remojansen** [comment]
Hi @thefabulousdev should I close this issue? thanks!

**Comment by lifenautjoe** [comment]
Whoops! I completely forgot, will get it done as soon as I get home.

**Comment by remojansen** [comment]
No worries :)
